["protostar.config"]
protostar_version = "0.2.4"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src"]

[profile.ci.protostar.shared_command_configs]
cairo_path = ["./lib/cairo_contracts/src"]
no_color = true
target = "src"

["protostar.contracts"]
attendance_nft = [
  "src/attendance_nft.cairo",
]
